apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: docker.io/jfranconeto/accounts:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: API_PORT
          value: "4000"
        - name: NODE_ENV
          value: "dev"