apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: accounts-rollouts
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: accounts-rollouts-canary
      stableService: accounts-rollouts-stable
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 2 # delay starting analysis run until setWeight: 20%
        args:
        - name: service-name
          value: accounts-rollouts-canary.develop.svc.cluster.local
      trafficRouting:
        istio:
          virtualService:
            name: meshvs
            routes:
            - accounts # At least one route is required
      steps:
      - setWeight: 10
      - pause: {duration: 1m}
      - setWeight: 20
      - pause: {duration: 1m}
      - setWeight: 40
      - pause: {duration: 1m}
      - setWeight: 80
      - pause: {duration: 1m}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
        istio-injection: enabled
    spec:
      containers:
      - name: accounts
        image: docker.io/jfranconeto/accounts:1.0
        ports:
        - name: http
          containerPort: 4000
          protocol: TCP
        env:
        - name: API_PORT
          value: "4000"
        - name: NODE_ENV
          value: "dev"