apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: accounts-authorization-policy
  namespace: develop
spec:
  selector:
    matchLabels:
      app: accounts
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]