apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshvs
spec:
  hosts:
  - "*"
  gateways:
  - kenlo-gateway
  http:
  - match:
    - uri:
        prefix: /accounts
    name: accounts  
    route:
    - destination:
        host: accounts-rollouts-stable
      weight: 100
    - destination:
        host: accounts-rollouts-canary 
      weight: 0